webapi:
  url: localhost:8081
  auth:
    username: iguazio
    password: iguazio
functions:
    ingest:
      name: "ingest"
      replicas: 1
      image:
        repository: levrado1/tsdb-ingest
        tag: "0.0.1"
    query:
      name: "query"
      replicas: 1
      image:
        repository: levrado1/tsdb-query
        tag: "0.0.1"
