apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: {{ .Values.functions.query.name }}
  labels:
    nuclio.io/project-name: nuclio-tsdb
spec:
  build:
    codeEntryType: image
  handler: main:Handler
  image: {{ .Values.functions.query.image.repository }}:{{ .Values.functions.query.image.tag }}
  replicas: {{ .Values.functions.query.replicas }}
  runtime: golang
  dataBindings:
    db0:
      class: v3io
      url: {{ .Values.webapi.url | quote }}
      secret: {{ .Values.webapi.auth.username }}:{{ .Values.webapi.auth.password }}
status:
  state: waitingForResourceConfiguration
