tsdb:
  path: mytsdb
webapi:
  url: localhost:8081
  auth:
    username: iguazio
    password: iguazio
project:
  displayName: TSDB functions
functions:
    ingest:
      readinessTimeoutSeconds: 180
      replicas: 1
      port: 32030
      ingress: {}
      image:
        repository: iguaziodocker/tsdb-ingest
        tag: 0.0.7
    query:
      readinessTimeoutSeconds: 180
      replicas: 1
      port: 32031
      ingress: {}
      image:
        repository: iguaziodocker/tsdb-query
        tag: 0.0.7
    kv:
      readinessTimeoutSeconds: 180
      replicas: 1
      port: 32032
      ingress: {}
      maxWorkers: 10
      image:
        repository: iguaziodocker/tsdb-query-kv
        tag: 0.0.7
